services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mern-vp-rabbitmq
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build: ./api
    container_name: mern-vp-api
    restart: always
    ports:
      - "3030:3030"
    environment:
      - PORT=3030
      - MONGO=mongodb+srv://memerlin90:LYyX217FP02iuCqV@pak.21cks.mongodb.net/?retryWrites=true&w=majority&appName=pak
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - JWT_SECRET=ganti_dengan_rahasia_jwt_yang_kuat
      - INTERNAL_KEY=mern-vp-internal-systemd-2026
      - ALLOWED_ORIGINS=https://healthtrajectory.cloud,https://api.healthtrajectory.cloud
    depends_on:
      - rabbitmq
    dns:
      - 103.253.213.134
      - 203.175.8.227

  backoffice:
    build: ./backoffice
    container_name: mern-vp-backoffice
    restart: always
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production

volumes:
  rabbitmq_data:
