services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mern-vp-rabbitmq
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build: ./api
    container_name: mern-vp-api
    restart: always
    ports:
      - "3030:3030"
    env_file:
      - ./api/.env
    environment:
      - PORT=3030
      - ALLOWED_ORIGINS=https://healthtrajectory.cloud,https://api.healthtrajectory.cloud
    depends_on:
      - rabbitmq
    dns:
      - 103.253.213.134
      - 203.175.8.227

  capar-web:
    build: ./capar-web
    container_name: mern-vp-capar-web
    restart: always
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production

volumes:
  rabbitmq_data:
